CREATE SCHEMA IF NOT EXISTS hw2;
SET search_path TO hw2;

DROP TABLE IF EXISTS hw2.work;
DROP TABLE IF EXISTS hw2.instrument;
DROP TABLE IF EXISTS hw2.composer;



CREATE TABLE hw2.composer
(
    composer_id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    varchar(30)                             NOT NULL,
    surname varchar(30)                             NOT NULL,
    country varchar(20)                             NOT NULL,
    CONSTRAINT pk_composer PRIMARY KEY (composer_id)
);

CREATE TABLE hw2.instrument
(
    instrument_id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(30)                             NOT NULL,
    CONSTRAINT pk_instrument PRIMARY KEY (instrument_id)
);

CREATE TABLE hw2.work
(
    work_id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         varchar(255)                             NOT NULL,
    composer_id   bigint                                  NOT NULL,
    instrument_id bigint                                  NOT NULL,
    difficulty    varchar(20)                             NOT NULL,

    CONSTRAINT pk_work PRIMARY KEY (work_id),

    CONSTRAINT chk_work_difficulty
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'VERY_HARD')),

    CONSTRAINT fk_work_composer
        FOREIGN KEY (composer_id)
            REFERENCES hw2.composer (composer_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_work_instrument
        FOREIGN KEY (instrument_id)
            REFERENCES hw2.instrument (instrument_id)
            ON DELETE RESTRICT
);
