-- schema is already hw2; keep explicit refs to be safe
CREATE SCHEMA IF NOT EXISTS hw2;

-- =========================
-- GENRE
-- =========================
CREATE TABLE hw2.genre
(
    genre_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     varchar(60) NOT NULL,

    CONSTRAINT pk_genre PRIMARY KEY (genre_id),
    CONSTRAINT uq_genre_name UNIQUE (name)
);

-- =========================
-- WORK <-> GENRE (M:N)
-- =========================
CREATE TABLE hw2.work_genre
(
    work_id  bigint NOT NULL,
    genre_id bigint NOT NULL,

    CONSTRAINT pk_work_genre PRIMARY KEY (work_id, genre_id),

    CONSTRAINT fk_work_genre_work
        FOREIGN KEY (work_id)
            REFERENCES hw2.work (work_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_work_genre_genre
        FOREIGN KEY (genre_id)
            REFERENCES hw2.genre (genre_id)
            ON DELETE RESTRICT
);

CREATE INDEX idx_work_genre_work_id  ON hw2.work_genre (work_id);
CREATE INDEX idx_work_genre_genre_id ON hw2.work_genre (genre_id);

-- =========================
-- RECORDING (1:N from work)
-- =========================
CREATE TABLE hw2.recording
(
    recording_id  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_id       bigint NOT NULL,

    performer     varchar(120) NOT NULL,
    label         varchar(120),
    recorded_at   date NOT NULL,
    duration_sec  integer NOT NULL,
    source_url    varchar(300),

    CONSTRAINT pk_recording PRIMARY KEY (recording_id),

    CONSTRAINT fk_recording_work
        FOREIGN KEY (work_id)
            REFERENCES hw2.work (work_id)
            ON DELETE CASCADE,

    CONSTRAINT ck_recording_duration_positive
        CHECK (duration_sec > 0)
);

CREATE INDEX idx_recording_work_id     ON hw2.recording (work_id);
CREATE INDEX idx_recording_recorded_at ON hw2.recording (recorded_at);
