hw2.datasource.driver=${PG_DRIVER:org.postgresql.Driver}
hw2.datasource.url=${PG_URL}
hw2.datasource.username=${PG_USER}
hw2.datasource.password=${PG_PASS}
hw2.mode=${APP_MODE:normal}

#????????? ????? ? VM Options
#-DPG_DRIVER=org.postgresql.Driver;
#-DPG_URL=jdbc:postgresql://localhost:5432/otus;
#-DPG_USER=otus;
#-DPG_PASS=otus;
#-DAPP_MODE=<clean>