CREATE TABLE public.composer
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    varchar(30)                             NOT NULL,
    surname varchar(30)                             NOT NULL,
    country varchar(20)                             NOT NULL,
    CONSTRAINT pk_composer PRIMARY KEY (id)
);

CREATE TABLE public.instrument
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(30)                             NOT NULL,
    CONSTRAINT pk_instrument PRIMARY KEY (id)
);

CREATE TABLE public.work
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         varchar(255)                             NOT NULL,
    composer_id   bigint                                  NOT NULL,
    instrument_id bigint                                  NOT NULL,
    difficulty    varchar(20)                             NOT NULL,

    CONSTRAINT pk_work PRIMARY KEY (id),

    CONSTRAINT chk_work_difficulty
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'VERY_HARD')),

    CONSTRAINT fk_work_composer
        FOREIGN KEY (composer_id)
            REFERENCES public.composer (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_work_instrument
        FOREIGN KEY (instrument_id)
            REFERENCES public.instrument (id)
            ON DELETE RESTRICT
);
